version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hiran@2001
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    networks:
      - urlshortener-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - urlshortener-network

  app:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    networks:
      - urlshortener-network

networks:
  urlshortener-network:
    driver: bridge
