version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - urlshortener-network
    command: redis-server --requirepass redispassword

  app:
    build: .
    container_name: url-shortener
    restart: always
    depends_on:
      - redis
    env_file:
      - /home/ubuntu/URL-Shortener-Solution/.env
    ports:
      - "5000:5000"
    networks:
      - urlshortener-network

networks:
  urlshortener-network:
    driver: bridge
